services:
  web:
    build:
      context: ./src
    ports:
      - "6767:6767"
    stop_signal: SIGINT
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=production
      - DATA_DIR=/data
